[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sudoku-solver"
version = "1.0.0"
description = "Solve Sudoku puzzles"
readme = "README.md"

[project.scripts]
sudokusolve = "sudoku_solver.__main__:main"