[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sudoku-solver"
version = "1.0.0"
description = "Solve Sudoku puzzles"
readme = "README.md"